### ISSUE TITLE
Why symmetric properties

### ISSUE THREAD

**Issue by alexdma** [DrPollo/read-it-datamodel#20]
All object properties in [REO_2.0.2.owl](../blob/master/REO_2.0.2.owl) are marked as Symmetric.

This would imply, for example in the case of `readP1` (has occupation), that if Charles Dickens has occupation Writer, then Writer also has occupation Charles Dickens.

What is the justification for all properties being symmetric?

**Comment by fvignale** [comment]
Sorry for the mistake. It has already been corrected but not yet downloaded !

**Comment by fvignale** [comment]
And you'll find a lot more of that kind.

**Comment by fvignale** [comment]
What is meant here is that Charles D. has occupation Writer, then Writer is occupation of Charles D.

**Comment by fvignale** [comment]
This mistake is to due to OntoME, the tool I worked with to design REO. 

The kind of property I want to use is of the  InverseObjectProperties kind. 

So, in Protege I added an InverseOf property to almost each one you can see in REO 2.0.2 and tick nothing for moment in Characteristics (thought of Functional). Tell me if I am wrong.

**Comment by alexdma** [comment]
> So, in Protege I added an InverseOf property to almost each one you can see in REO 2.0.2 and tick nothing for moment in Characteristics (thought of Functional). Tell me if I am wrong.

No, in fact using pairs of inverse object properties is among the most commonly adopted ontology design patterns, so that would be the way to go. Some might indeed turn out to be functional - I'll give them a more thorough look later.

**Comment by fvignale** [comment]
Thank you. I'll let you know when the next version is uploaded.

**Comment by fvignale** [comment]
Dear Alessandro, I have uploaded a new version of REO (2.4). Let me know what you think of it. François

**Comment by alexdma** [comment]
That's fine @fvignale - it's better not to flag any of them now and check for each later, whether it should be functional, symmetric etc.
